export const LATEST_DEVICES_REQUEST = 'LATEST_DEVICES_REQUEST'
export const LATEST_DEVICES_SUCCESS = 'LATEST_DEVICES_SUCCESS'
export const LATEST_DEVICES_FAIL = 'LATEST_DEVICES_FAIL'

export const DEVICE_DETAILS_REQUEST = 'DEVICE_DETAILS_REQUEST'
export const DEVICE_DETAILS_SUCCESS = 'DEVICE_DETAILS_SUCCESS'
export const DEVICE_DETAILS_FAIL = 'DEVICE_DETAILS_FAIL'

